const {chromium}=require('playwright') // npm install playwright && npx playwright install chromium;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8791/workspace.html');
 await page.getByRole('button',{name:'Connect worker',exact:true}).click();
 await page.locator('.worker-dialog input[name=url]').fill('http://127.0.0.1:8792');
 await page.locator('.worker-dialog input[name=token]').fill('browser-fixture-token-not-a-secret-0000');
 await page.getByRole('button',{name:'Test and connect'}).click();
 await page.waitForFunction(()=>!document.querySelector('.worker-dialog').open);
 await page.locator('#set-name').fill('Hosted workflow QA');
 await page.locator('.prompt-text').fill('Decide between RUN and WAIT.');await page.locator('.answer-text').fill('RUN\nWAIT');
 await page.locator('#save-set').click();await page.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('Saved'));
 const budget=await page.locator('#batch-budget').innerText();
 if(!await page.locator('#start-batch').isDisabled())throw Error('Batch enabled without model');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#set-list').textContent.includes('Hosted workflow QA'));
 await page.getByRole('button',{name:/Hosted workflow QA/}).click();
 await page.waitForFunction(()=>document.querySelector('.prompt-text').value==='Decide between RUN and WAIT.');
 const link=page.locator('.configure-prompt').first();await link.click();await page.waitForFunction(()=>document.querySelector('#question').value==='Decide between RUN and WAIT.');
 if(await page.locator('#model-id').inputValue())throw Error('Personal default model');
 await page.goto('http://127.0.0.1:8791/workspace.html');await page.waitForTimeout(600);
 await page.screenshot({path:'reports/public-workflow/hosted-workspace.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'reports/public-workflow/hosted-workspace-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)throw Error('Mobile overflow');
 const api=await page.evaluate(async()=>{let response=await window.workerFetch('/api/live/prompt-sets');return response.json();});
 if(api.sets.length!==1)throw Error('Wrong worker data');
 await page.goto('http://127.0.0.1:8791/observatory.html?run=352516a7e5184bc6841d8eb075ecb09a');await page.waitForSelector('#evidence:not([hidden])');
 const download=page.waitForEvent('download');await page.locator('#download').click();const file=await download;if(!file.suggestedFilename().endsWith('.json'))throw Error('Evidence download failed');
 await page.locator('#refinement-disclosure').click();await page.locator('#ref-reference').click();if(await page.locator('#ref-samples').inputValue()!=='100')throw Error('Reference preset missing');if(!await page.locator('#ref-run').isDisabled())throw Error('Refine enabled without source model');
 require('fs').writeFileSync('reports/public-workflow/hosted-qa.json',JSON.stringify({passed:true,budget,checks:['cross-origin authenticated connection','remote prompt set save/reload','saved prompt into Configure','empty model defaults','batch disabled without model','mobile width','authenticated evidence download','reference budget preset/no automatic compute'],errors},null,2));
 if(errors.length)throw Error(errors.join('\n'));await browser.close();console.log('Hosted frontend / separate authenticated worker QA passed');
})().catch(e=>{console.error(e);process.exit(1)});
